export const REQUEST_GITHUB_DATA_PENDING = 'REQUEST_GITHUB_DATA_PENDING';
export const REQUEST_GITHUB_DATA_SUCCESS = 'REQUEST_GITHUB_DATA_SUCCESS';
export const REQUEST_GITHUB_DATA_FAILED = 'REQUEST_GITHUB_DATA_FAILED';